version: '3.7'

services:
  app:
    build: ./src
    depends_on:
      - database
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
    ports:
      - 3000:3000
    volumes:
      - ./src:/app

  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    volumes:
      - database_volume:/var/lib/postgresql/data

  ioc:
    build:
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
      context: ./terraform
    volumes:
      - ${AWS_CREDENTIALS_PATH}:/root/.aws

volumes:
  database_volume: {}
