version: '3.7'

services:
  app:
    build: ./src
    ports:
      - 3000:3000
    volumes:
      - ./src:/app

  ioc:
    build:
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
      context: ./terraform
